spring.config.activate.on-profile=dev
server.port=8080

# DataSource setting (MariaDB)
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/schm_com?rewriteBatchedStatements=true
spring.datasource.username=root
spring.datasource.password=deer

#JPA setting
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Upload Path
File.Store.Path=C:/home/upload

#Page config
Globals.pageUnit=10
Globals.pageSize=10

spring.thymeleaf.cache=false

#Redis Setting
spring.data.redis.host=1.233.95.140
spring.data.redis.port=50055
spring.data.redis.password=epqmwlttn1q2w3e
Globals.redis.dataBase=15